freebsd_instance:
  image_family: freebsd-13-2

freebsd_task:
  env:
    matrix:
      - OCAML_VERSION: 4.14.2
  pkg_install_script: pkg install -y ocaml-opam gmake bash
  ocaml_script: opam init -a --comp=$OCAML_VERSION
  mirage_script: eval `opam env` && opam install --confirm-level=unsafe-yes "mirage>=4.5.0"
  configure_script: eval `opam env` && mirage configure -t hvt
  depend_script: eval `opam env` && gmake depend
  build_script: eval `opam env` && gmake build
  traceroute_artifacts:
    path: dist/traceroute.hvt
